### ISSUE TITLE
undefined method `register_preprocessor'

### ISSUE THREAD

**Issue by allthesignals** [Semantic-Org/Semantic-UI-Rails-LESS#24]
Using rails 4.2.3

`rails s` and `rails generate semantic_ui:install` throw this:

```
/Users/mattgardner/.rvm/gems/ruby-2.0.0-p598/gems/less-rails-2.7.0/lib/less/rails/railtie.rb:19:in `block in <class:Railtie>': undefined method `register_preprocessor' for nil:NilClass (NoMethodError)
	from /Users/mattgardner/.rvm/gems/ruby-2.0.0-p598/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/mattgardner/.rvm/gems/ruby-2.0.0-p598/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `run'
	from /Users/mattgardner/.rvm/gems/ruby-2.0.0-p598/gems/railties-4.2.3/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/mattgardner/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
	from /Users/mattgardner/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
	from /Users/mattgardner/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
	from /Users/mattgardner/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
	from /Users/mattgardner/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/tsort.rb:180:in `each'
	from /Users/mattgardner/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
	from /Users/mattgardner/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
	from /Users/mattgardner/.rvm/gems/ruby-2.0.0-p598/gems/railties-4.2.3/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/mattgardner/.rvm/gems/ruby-2.0.0-p598/gems/railties-4.2.3/lib/rails/application.rb:352:in `initialize!'
	from /Users/mattgardner/Development/vignette/config/environment.rb:5:in `<top (required)>'
	from /Users/mattgardner/.rvm/gems/ruby-2.0.0-p598/gems/spring-1.6.2/lib/spring/application.rb:92:in `require'
	from /Users/mattgardner/.rvm/gems/ruby-2.0.0-p598/gems/spring-1.6.2/lib/spring/application.rb:92:in `preload'
	from /Users/mattgardner/.rvm/gems/ruby-2.0.0-p598/gems/spring-1.6.2/lib/spring/application.rb:143:in `serve'
	from /Users/mattgardner/.rvm/gems/ruby-2.0.0-p598/gems/spring-1.6.2/lib/spring/application.rb:131:in `block in run'
	from /Users/mattgardner/.rvm/gems/ruby-2.0.0-p598/gems/spring-1.6.2/lib/spring/application.rb:125:in `loop'
	from /Users/mattgardner/.rvm/gems/ruby-2.0.0-p598/gems/spring-1.6.2/lib/spring/application.rb:125:in `run'
	from /Users/mattgardner/.rvm/gems/ruby-2.0.0-p598/gems/spring-1.6.2/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/mattgardner/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

**Comment by allthesignals** [comment]
`gem 'sprockets', '~> 2'`
then 
`bundle update`
seems to fix this. I thought the Appraisals file was doing this?
